version: "3.8"

services:
  neo4j:
    image: neo4j:5.5.0-community
    container_name: vaultbot-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}

  mongo:
    image: mongo:6.0.4
    container_name: vaultbot-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  vaultbot:
    container_name: vaultbot-discord
    build: .
    environment:
      ENVIRONMENT: "docker"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_PLAYLIST_ID: ${SPOTIFY_PLAYLIST_ID}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}

volumes:
  neo4j_data:
  mongo_data: