name: Curated Playlists

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  genre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Build
        run: go build -o bin/genre ./cmd/genre

      - name: Run
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          GENRE_SPOTIFY_PLAYLIST_ID: ${{ secrets.GENRE_SPOTIFY_PLAYLIST_ID }}
          HIGH_SCORES_SPOTIFY_PLAYLIST_ID: ${{ secrets.HIGH_SCORES_SPOTIFY_PLAYLIST_ID }}
          THROWBACK_SPOTIFY_PLAYLIST_ID: ${{ secrets.THROWBACK_SPOTIFY_PLAYLIST_ID }}
          VARIETY_SPOTIFY_PLAYLIST_ID: ${{ secrets.VARIETY_SPOTIFY_PLAYLIST_ID }}
          POSTGRES_HOST: ${{ secrets.NEON_HOST }}
          POSTGRES_PORT: ${{ secrets.NEON_PORT }}
          POSTGRES_USER: ${{ secrets.NEON_USER }}
          POSTGRES_PASSWORD: ${{ secrets.NEON_PASSWORD }}
          POSTGRES_DB: ${{ secrets.NEON_DB }}
        run: ./bin/genre

  highscores:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Build
        run: go build -o bin/highscores ./cmd/highscores

      - name: Run
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          GENRE_SPOTIFY_PLAYLIST_ID: ${{ secrets.GENRE_SPOTIFY_PLAYLIST_ID }}
          HIGH_SCORES_SPOTIFY_PLAYLIST_ID: ${{ secrets.HIGH_SCORES_SPOTIFY_PLAYLIST_ID }}
          THROWBACK_SPOTIFY_PLAYLIST_ID: ${{ secrets.THROWBACK_SPOTIFY_PLAYLIST_ID }}
          VARIETY_SPOTIFY_PLAYLIST_ID: ${{ secrets.VARIETY_SPOTIFY_PLAYLIST_ID }}
          POSTGRES_HOST: ${{ secrets.NEON_HOST }}
          POSTGRES_PORT: ${{ secrets.NEON_PORT }}
          POSTGRES_USER: ${{ secrets.NEON_USER }}
          POSTGRES_PASSWORD: ${{ secrets.NEON_PASSWORD }}
          POSTGRES_DB: ${{ secrets.NEON_DB }}
        run: ./bin/highscores

  throwback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Build
        run: go build -o bin/throwback ./cmd/throwback

      - name: Run
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          GENRE_SPOTIFY_PLAYLIST_ID: ${{ secrets.GENRE_SPOTIFY_PLAYLIST_ID }}
          HIGH_SCORES_SPOTIFY_PLAYLIST_ID: ${{ secrets.HIGH_SCORES_SPOTIFY_PLAYLIST_ID }}
          THROWBACK_SPOTIFY_PLAYLIST_ID: ${{ secrets.THROWBACK_SPOTIFY_PLAYLIST_ID }}
          VARIETY_SPOTIFY_PLAYLIST_ID: ${{ secrets.VARIETY_SPOTIFY_PLAYLIST_ID }}
          POSTGRES_HOST: ${{ secrets.NEON_HOST }}
          POSTGRES_PORT: ${{ secrets.NEON_PORT }}
          POSTGRES_USER: ${{ secrets.NEON_USER }}
          POSTGRES_PASSWORD: ${{ secrets.NEON_PASSWORD }}
          POSTGRES_DB: ${{ secrets.NEON_DB }}
        run: ./bin/throwback

  variety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Build
        run: go build -o bin/variety ./cmd/variety

      - name: Run
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          GENRE_SPOTIFY_PLAYLIST_ID: ${{ secrets.GENRE_SPOTIFY_PLAYLIST_ID }}
          HIGH_SCORES_SPOTIFY_PLAYLIST_ID: ${{ secrets.HIGH_SCORES_SPOTIFY_PLAYLIST_ID }}
          THROWBACK_SPOTIFY_PLAYLIST_ID: ${{ secrets.THROWBACK_SPOTIFY_PLAYLIST_ID }}
          VARIETY_SPOTIFY_PLAYLIST_ID: ${{ secrets.VARIETY_SPOTIFY_PLAYLIST_ID }}
          POSTGRES_HOST: ${{ secrets.NEON_HOST }}
          POSTGRES_PORT: ${{ secrets.NEON_PORT }}
          POSTGRES_USER: ${{ secrets.NEON_USER }}
          POSTGRES_PASSWORD: ${{ secrets.NEON_PASSWORD }}
          POSTGRES_DB: ${{ secrets.NEON_DB }}
        run: ./bin/variety
