name: Purge Expired Tracks

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Build
        run: go build -o bin/purge ./cmd/purge

      - name: Run
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          GENRE_SPOTIFY_PLAYLIST_ID: ${{ secrets.GENRE_SPOTIFY_PLAYLIST_ID }}
          HIGH_SCORES_SPOTIFY_PLAYLIST_ID: ${{ secrets.HIGH_SCORES_SPOTIFY_PLAYLIST_ID }}
          THROWBACK_SPOTIFY_PLAYLIST_ID: ${{ secrets.THROWBACK_SPOTIFY_PLAYLIST_ID }}
          VARIETY_SPOTIFY_PLAYLIST_ID: ${{ secrets.VARIETY_SPOTIFY_PLAYLIST_ID }}
        run: ./bin/purge
