name: "Terraform CI/CD"

on:
  push:
    branches:
      - main  # Runs Terraform Apply when merging to main
  pull_request:
    paths:
      - 'infra/**'  # Runs only if files in infra/ change

jobs:
  terraform:
    name: "Terraform Validation & Deployment"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

      - name: Validate Terraform
        working-directory: infra
        run: terraform validate

      - name: Plan Terraform Changes
        working-directory: infra
        run: terraform plan
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_api_secret_key: ${{ secrets.TF_VAR_api_secret_key }}

      # Only apply changes if on main branch (i.e., after PR merge)
      - name: Apply Terraform Changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: infra
        run: terraform apply -auto-approve
        env:
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_api_secret_key: ${{ secrets.TF_VAR_api_secret_key }}
