import { defineConfig } from "vitest/config";

export default defineConfig({
	esbuild: {
		// Provide compiler options inline so esbuild never needs to resolve
		// tsconfig.json → .svelte-kit/tsconfig.json (generated by svelte-kit sync,
		// absent in CI until that command runs).
		tsconfigRaw: {
			compilerOptions: {
				strict: true,
				esModuleInterop: true,
				moduleResolution: "bundler",
				module: "ESNext",
				target: "ESNext",
			},
		},
	},
	test: {
		include: ["src/**/*.test.ts"],
	},
});
